export const teamsArray = [
  {
    "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
    "team_logo" :"https://1000logos.net/wp-content/uploads/2024/03/Chennai-Super-Kings-Logo.png",
    "players": [
      {
        "id": "csk001",
        "name": "MS Dhoni",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Wicketkeeper",
        "role_short_form": "Wicketkeeper",
        "dob": "1981-07-07",
        "age": 42,
        "country": "India",
        "matches": 204,
        "runs": 4632,
        "highest_score": 84,
        "average": 40.99,
        "strike_rate": 136.67,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/57.png",
        "points": 100
      },
      {
        "id": "csk002",
        "name": "Suresh Raina",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Batsman",
        "role_short_form": "Batsman",
        "dob": "1986-11-27",
        "age": 38,
        "country": "India",
        "matches": 193,
        "runs": 5491,
        "highest_score": 100,
        "average": 33.07,
        "strike_rate": 137.14,
        "image": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/14.png",
        "points": 95
      },
      {
        "id": "csk003",
        "name": "Ravindra Jadeja",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "All-rounder",
        "role_short_form": "All-rounder",
        "dob": "1988-12-06",
        "age": 35,
        "country": "India",
        "matches": 192,
        "runs": 2159,
        "highest_score": 62,
        "average": 27.76,
        "strike_rate": 130.94,
        "wickets": 120,
        "best_bowling": "5/16",
        "economy_rate": 7.6,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/46.png",
        "points": 90
      },
      {
        "id": "csk004",
        "name": "Deepak Chahar",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Bowler",
        "role_short_form": "Bowler",
        "dob": "1992-08-07",
        "age": 32,
        "country": "India",
        "matches": 58,
        "wickets": 61,
        "best_bowling": "4/29",
        "economy_rate": 7.67,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/91.png",
        "points": 85
      },
      {
        "id": "csk005",
        "name": "Shardul Thakur",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Bowler",
        "role_short_form": "Bowler",
        "dob": "1991-10-16",
        "age": 32,
        "country": "India",
        "matches": 49,
        "wickets": 51,
        "best_bowling": "3/19",
        "economy_rate": 8.94,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/105.png",
        "points": 80
      },
      {
        "id": "csk006",
        "name": "Faf du Plessis",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Batsman",
        "role_short_form": "Batsman",
        "dob": "1984-07-13",
        "age": 39,
        "country": "South Africa",
        "matches": 100,
        "runs": 2661,
        "highest_score": 96,
        "average": 33.26,
        "strike_rate": 128.01,
        "image": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/24.png",
        "points": 85
      },
      {
        "id": "csk007",
        "name": "Imran Tahir",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Bowler",
        "role_short_form": "Bowler",
        "dob": "1979-03-27",
        "age": 45,
        "country": "South Africa",
        "matches": 56,
        "wickets": 82,
        "best_bowling": "4/12",
        "economy_rate": 7.96,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCfKUt-lVD3Ml-5JZP4APklgJToSnOb0TzJ_kOfdwOQgf7LXifr7mRDo2fIoIwlCYRvxw&usqp=CAU",
        "points": 85
      },
      {
        "id": "csk008",
        "name": "Ruturaj Gaikwad",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Batsman",
        "role_short_form": "Batsman",
        "dob": "1997-01-31",
        "age": 27,
        "country": "India",
        "matches": 31,
        "runs": 843,
        "highest_score": 88,
        "average": 31.22,
        "strike_rate": 131.41,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/102.png",
        "points": 80
      },
      {
        "id": "csk009",
        "name": "Sam Curran",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "All-rounder",
        "role_short_form": "All-rounder",
        "dob": "1998-06-03",
        "age": 25,
        "country": "England",
        "matches": 33,
        "runs": 615,
        "highest_score": 52,
        "average": 24.6,
        "strike_rate": 137.17,
        "wickets": 32,
        "best_bowling": "3/19",
        "economy_rate": 8.18,
        "image": "https://parimatchnews.com/wp-content/uploads/2020/11/Sam-Curran.png",
        "points": 85
      },
      {
        "id": "csk010",
        "name": "Moeen Ali",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "All-rounder",
        "role_short_form": "All-rounder",
        "dob": "1987-06-18",
        "age": 36,
        "country": "England",
        "matches": 35,
        "runs": 309,
        "highest_score": 25,
        "average": 20.6,
        "strike_rate": 135.68,
        "wickets": 16,
        "best_bowling": "2/18",
        "economy_rate": 7.13,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/206.png",
        "points": 80
      },
      {
        "id": "csk011",
        "name": "Shivam Dube",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "All-rounder",
        "role_short_form": "All-rounder",
        "dob": "1993-06-26",
        "age": 30,
        "country": "West Indies",
        "matches": 65,
        "runs": 1502,
        "strike_rate": 146.68,
        "best_bowling": "2/15",
        "economy_rate": 7.13,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/211.png",
        "points": 80
      },
      {
        "id": "csk012",
        "name": "Tushar Deshpande",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Bowler",
        "role_short_form": "Bowler",
        "dob": "15 May 1995",
        "age": 29,
        "country": "India",
        "matches": 36,
        "runs": 1243,
        "strike_rate": 150.00,
        "best_bowling": "4/27",
        "economy_rate": 9.65,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/539.png",
        "points": 85
      },
      {
        "id": "csk013",
        "name": "Avanish Rao Aravelly",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Wicketkeeper",
        "role_short_form": "Wicketkeeper",
        "dob": "02 June 2005",
        "age": 19,
        "country": "India",
        "matches": 0,
        "runs": 0,
        "strike_rate": 0.00,
        "best_bowling": "-",
        "economy_rate": 0,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/2794.png",
        "points": 0
      },
      {
        "id": "csk014",
        "name": "Ajinkya Rahane",
        "team_short_form": "CSK",
    "team_full_form": "Chennai Super Kings",
        "role": "Batsman",
        "role_short_form": "Batsman",
        "dob": "06 June 1988",
        "age": 36,
        "country": "India",
        "matches": 185,
        "runs": 4642,
        "strike_rate": 123.42,
        "best_bowling": "-",
        "economy_rate": 5.00,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/44.png",
        "points": 80
      }
    ]
  },
  {
    "team_short_form": "RCB",
    "team_full_form": "Royal Challengers Bangalore",
    "team_logo" :"https://1000logos.net/wp-content/uploads/2024/03/Royal-Challengers-Bengaluru-Logo.png",
    "players": [
      {
        "id": "rcb001",
        "name": "Virat Kohli",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Batsman",
        "role_short_form": "Batsman",
        "dob": "1988-11-05",
        "age": 35,
        "country": "India",
        "matches": 252,
        "runs": 8004,
        "highest_score": 113,
        "average": 38.16,
        "strike_rate": 130.41,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/2.png",
        "points": 100
      },
      {
        "id": "rcb002",
        "name": "AB de Villiers",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Batsman",
        "role_short_form": "Batsman",
        "dob": "1984-02-17",
        "age": 40,
        "country": "South Africa",
        "matches": 184,
        "runs": 4849,
        "highest_score": 133,
        "average": 40.4,
        "strike_rate": 151.91,
        "image": "https://cricclubs.com/documentsRep/profilePics/1d20c46a-2c7d-43ed-b4f4-48387550f418.png",
        "points": 95
      },
      {
        "id": "rcb003",
        "name": "Glenn Maxwell",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "All-rounder",
        "role_short_form": "All-rounder",
        "dob": "1988-10-14",
        "age": 35,
        "country": "Australia",
        "matches": 90,
        "runs": 1687,
        "highest_score": 95,
        "average": 22.49,
        "strike_rate": 152.52,
        "wickets": 18,
        "best_bowling": "2/15",
        "economy_rate": 8.78,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/28.png",
        "points": 90
      },
      {
        "id": "rcb004",
        "name": "Devdutt Padikkal",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Batsman",
        "role_short_form": "Batsman",
        "dob": "2000-07-07",
        "age": 24,
        "country": "India",
        "matches": 32,
        "runs": 1022,
        "highest_score": 101,
        "average": 33.13,
        "strike_rate": 134.18,
        "image": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/5430.png",
        "points": 85
      },
      {
        "id": "rcb005",
        "name": "Yuzvendra Chahal",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Bowler",
        "role_short_form": "Bowler",
        "dob": "1990-07-23",
        "age": 33,
        "country": "India",
        "matches": 109,
        "wickets": 146,
        "best_bowling": "4/25",
        "economy_rate": 7.67,
        "image": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/111.png",
        "points": 85
      },
      {
        "id": "rcb006",
        "name": "Kyle Jamieson",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Wicketkeeper",
        "role_short_form": "Wicketkeeper",
        "dob": "1994-12-30",
        "age": 29,
        "country": "New Zealand",
        "matches": 8,
        "runs": 73,
        "highest_score": 25,
        "average": 10.42,
        "strike_rate": 163.63,
        "wickets": 9,
        "best_bowling": "3/30",
        "economy_rate": 8.66,
        "image": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/1616.png",
        "points": 80
      },
      {
        "id": "rcb007",
        "name": "Washington Sundar",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "All-rounder",
        "role_short_form": "All-rounder",
        "dob": "1999-10-05",
        "age": 24,
        "country": "India",
        "matches": 42,
        "runs": 186,
        "highest_score": 35,
        "average": 12.4,
        "strike_rate": 123.18,
        "wickets": 24,
        "best_bowling": "3/16",
        "economy_rate": 6.96,
        "image": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/2973.png",
        "points": 80
      },
      {
        "id": "rcb008",
        "name": "Mohammed Siraj",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Bowler",
        "role_short_form": "Bowler",
        "dob": "1994-03-13",
        "age": 28,
        "country": "India",
        "matches": 46,
        "wickets": 52,
        "best_bowling": "3/8",
        "economy_rate": 8.35,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/63.png",
        "points": 85
      },
      {
        "id": "rcb009",
        "name": "Daniel Sams",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Wicketkeeper",
        "role_short_form": "Wicketkeeper",
        "dob": "1992-10-27",
        "age": 31,
        "country": "Australia",
        "matches": 3,
        "runs": 22,
        "highest_score": 9,
        "average": 7.33,
        "strike_rate": 73.33,
        "wickets": 3,
        "best_bowling": "2/25",
        "economy_rate": 9.6,
        "image": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/4649.png",
        "points": 80
      },
      {
        "id": "rcb010",
        "name": "Kane Richardson",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Bowler",
        "role_short_form": "Bowler",
        "dob": "1991-02-12",
        "age": 31,
        "country": "Australia",
        "matches": 14,
        "wickets": 17,
        "best_bowling": "3/13",
        "economy_rate": 8.4,
        "image": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/798.png",
        "points": 80
      },
      {
        "id": "rcb011",
        "name": "Himanshu Sharma",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Bowler",
        "role_short_form": "Bowler",
        "dob": "06 June 1998",
        "age": 25,
        "country":"India",
        "matches": 2,
        "wickets": 0,
        "best_bowling": "0/28",
        "economy_rate": 11.40,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/1568.png",
        "points": 80
      },
      {
        "id": "rcb012",
        "name": "Manoj Bhandage",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "Wicketkeeper",
        "role_short_form": "Wicketkeeper",
        "dob": "05 October 1998",
        "age": 27,
        "country":"India",
        "matches": 0,
        "wickets": 0,
        "best_bowling": "0/28",
        "economy_rate": 0,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/1485.png",
        "points": 0
      },
      {
        "id": "rcb013",
        "name": "Mahipal Lomror",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "All-rounder",
        "role_short_form": "All-rounder",
        "dob": "16 November 1999",
        "age": 25,
        "country":"India",
        "matches": 40,
        "wickets": 1,
        "best_bowling": "1/22",
        "economy_rate": 8.47,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/184.png",
        "points": 80
      },
      {
        "id": "rcb014",
        "name": "Mayank Dagar",
        "team_short_form": "RCB",
        "team_full_form": "Royal Challengers Bangalore",
        "role": "All-rounder",
        "role_short_form": "All-rounder",
        "dob": "11 November 1996",
        "age": 31,
        "country":"India",
        "matches": 8,
        "wickets": 2,
        "best_bowling": "1/22",
        "economy_rate": 8.89,
        "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/1547.png",
        "points": 80
      }
    ]
  }
];