// {
//     "team_short_form": "CSK",
//     "team_full_form": "Chennai Super Kings",
//     "players": [
//       {
//         "id": "csk001",
//         "name": "MS Dhoni",
//         "role": "Wicketkeeper-batsman",
//         "role_short_form": "WK-Batsman",
//         "dob": "1981-07-07",
//         "age": 42,
//         "country": "India",
//         "matches": 204,
//         "runs": 4632,
//         "highest_score": 84,
//         "average": 40.99,
//         "strike_rate": 136.67,
//         "image": "ms_dhoni.jpg",
//         "points": 100
//       },
//       {
//         "id": "csk002",
//         "name": "Suresh Raina",
//         "role": "Batsman",
//         "role_short_form": "Batsman",
//         "dob": "1986-11-27",
//         "age": 38,
//         "country": "India",
//         "matches": 193,
//         "runs": 5491,
//         "highest_score": 100,
//         "average": 33.07,
//         "strike_rate": 137.14,
//         "image": "suresh_raina.jpg",
//         "points": 95
//       },
//       {
//         "id": "csk003",
//         "name": "Ravindra Jadeja",
//         "role": "All-rounder",
//         "role_short_form": "All-rounder",
//         "dob": "1988-12-06",
//         "age": 35,
//         "country": "India",
//         "matches": 192,
//         "runs": 2159,
//         "highest_score": 62,
//         "average": 27.76,
//         "strike_rate": 130.94,
//         "wickets": 120,
//         "best_bowling": "5/16",
//         "economy_rate": 7.6,
//         "image": "ravindra_jadeja.jpg",
//         "points": 90
//       },
//       {
//         "id": "csk004",
//         "name": "Deepak Chahar",
//         "role": "Bowler",
//         "role_short_form": "Bowler",
//         "dob": "1992-08-07",
//         "age": 32,
//         "country": "India",
//         "matches": 58,
//         "wickets": 61,
//         "best_bowling": "4/29",
//         "economy_rate": 7.67,
//         "image": "deepak_chahar.jpg",
//         "points": 85
//       },
//       {
//         "id": "csk005",
//         "name": "Shardul Thakur",
//         "role": "Bowler",
//         "role_short_form": "Bowler",
//         "dob": "1991-10-16",
//         "age": 32,
//         "country": "India",
//         "matches": 49,
//         "wickets": 51,
//         "best_bowling": "3/19",
//         "economy_rate": 8.94,
//         "image": "shardul_thakur.jpg",
//         "points": 80
//       },
//       {
//         "id": "csk006",
//         "name": "Faf du Plessis",
//         "role": "Batsman",
//         "role_short_form": "Batsman",
//         "dob": "1984-07-13",
//         "age": 39,
//         "country": "South Africa",
//         "matches": 100,
//         "runs": 2661,
//         "highest_score": 96,
//         "average": 33.26,
//         "strike_rate": 128.01,
//         "image": "faf_du_plessis.jpg",
//         "points": 85
//       },
//       {
//         "id": "csk007",
//         "name": "Imran Tahir",
//         "role": "Bowler",
//         "role_short_form": "Bowler",
//         "dob": "1979-03-27",
//         "age": 45,
//         "country": "South Africa",
//         "matches": 56,
//         "wickets": 82,
//         "best_bowling": "4/12",
//         "economy_rate": 7.96,
//         "image": "imran_tahir.jpg",
//         "points": 85
//       },
//       {
//         "id": "csk008",
//         "name": "Ruturaj Gaikwad",
//         "role": "Batsman",
//         "role_short_form": "Batsman",
//         "dob": "1997-01-31",
//         "age": 27,
//         "country": "India",
//         "matches": 31,
//         "runs": 843,
//         "highest_score": 88,
//         "average": 31.22,
//         "strike_rate": 131.41,
//         "image": "ruturaj_gaikwad.jpg",
//         "points": 80
//       },
//       {
//         "id": "csk009",
//         "name": "Sam Curran",
//         "role": "All-rounder",
//         "role_short_form": "All-rounder",
//         "dob": "1998-06-03",
//         "age": 25,
//         "country": "England",
//         "matches": 33,
//         "runs": 615,
//         "highest_score": 52,
//         "average": 24.6,
//         "strike_rate": 137.17,
//         "wickets": 32,
//         "best_bowling": "3/19",
//         "economy_rate": 8.18,
//         "image": "sam_curran.jpg",
//         "points": 85
//       },
//       {
//         "id": "csk010",
//         "name": "Moeen Ali",
//         "role": "All-rounder",
//         "role_short_form": "All-rounder",
//         "dob": "1987-06-18",
//         "age": 36,
//         "country": "England",
//         "matches": 35,
//         "runs": 309,
//         "highest_score": 25,
//         "average": 20.6,
//         "strike_rate": 135.68,
//         "wickets": 16,
//         "best_bowling": "2/18",
//         "economy_rate": 7.13,
//         "image": "moeen_ali.jpg",
//         "points": 80
//       },
//       {
//         "id": "csk011",
//         "name": "Shivam Dube",
//         "role": "All-rounder",
//         "role_short_form": "All-rounder",
//         "dob": "1993-06-26",
//         "age": 30,
//         "country": "West Indies",
//         "matches": 65,
//         "runs": 1502,
//         "strike_rate": 146.68,
//         "best_bowling": "2/15",
//         "economy_rate": 7.13,
//         "image": "Shivam Dube.jpg",
//         "points": 80
//       }
//     ]
//   }